### ISSUE TITLE
gwu2 ist nicht in der nodes.json

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/freifunkmuc.github.io#110]
Hallo,

gwu2 ist nicht in der nodes.json

daher keine VPN Anzeige in den diversen Tools.
(z.B. http://y.pacher.com/ffmap/nodelist/ [Test frei nach: https://github.com/freifunkMUC/nodelist])

Servus
Christian

**Comment by fpletz** [comment]
Siehe https://github.com/freifunkMUC/puppet-ffm/issues/36
