### ISSUE TITLE
Wiki-Verlinkung auf die Startseite

### ISSUE THREAD

**Issue by dasenke** [freifunkMUC/freifunkmuc.github.io#116]
Ich denke das Wiki ist inzwischen sehr umfangreich und damit hilfreich und IMHO auf der HP viel zu weit hinten im Menü versteckt. Kann man das nicht deutlich weiter vorne oder auf der Startseite z. B. rechts unter den Terminen verlinken?

**Comment by DenkBrettl** [comment]
Dem kann ich nur zustimmen!

**Comment by midzer** [comment]
Ich würd eher Wiki aus Dienste rausnehmen und eine Ebene höher als neuen Punkt im Menü einbaun

**Comment by chris007de** [comment]
Habs einfach mal gemacht (d345c00da6f78995069c243c8318d403f520d3aa), wenns Proteststuerme gibt oder auf bestimmten Devices nun das Layout zerfetzt weil die Linkbar so lange ist kann mans ja wieder reverten.
