### ISSUE TITLE
Knotenkarte link in FAQ kaputt

### ISSUE THREAD

**Issue by nickel715** [freifunkMUC/freifunkmuc.github.io#118]
Aus mir unerklärlichen gründen wird in den FAQs unter `Wo stehen schon Freifunk-Router?` der Knotenkarte link nicht korrekt dargestellt, unter `Ich möchte meinen Knoten Remote administrieren. Geht das?` z.b. wird der link aber korrekt dargestellt.

**Comment by midzer** [comment]
Kann ich lokal mit Jekyll 2.5.3 gebaut bestätigen
