### ISSUE TITLE
Kein factory image für Allnet router

### ISSUE THREAD

**Issue by midzer** [freifunkMUC/freifunkmuc.github.io#121]
Nachm baun der images fällt für den Allnet ALL0315N kein factory image raus. Dementsprechend ist der Link zur firmware kaputt.

sysupgrade image ist vorhanden.

**Comment by chris007de** [comment]
Der Router hat ab Werk OpenWRT installiert, daher ist factory == sysupgrade.
http://www.allnet.de/de/allnet-brand/produkte/alle-produkte/p/allnet-all0315n-300mbit-openwrt-outdoor-apbridge/

Proposed fix:
post build: cp sysupgrade.bin factory.bin

**Comment by midzer** [comment]
Gleiche Situation beim 8devices carambola2 board

**Comment by privatereese** [comment]
Wäre zu beheben mit einer Fehlermeldung, wenn das entsprechende Image nicht verfügbar ist, siehe Kommentare PR #159
