### ISSUE TITLE
smtp abgehend aus muenchen.freifunk.net

### ISSUE THREAD

**Issue by gurucubano** [freifunkMUC/freifunkmuc.github.io#122]
Hallo,
wenn ich mit meinem netbook mit einem Knoten von muenchen.freifunk.net verbunden bin, kann ich keine mails per SMTP verschicken ... ist das so gewollt? Gruss

matthias

**Comment by midzer** [comment]
E-Mail sollte nicht geblockt sein. Hab grade eine Testmail ausm Umland Segment mit nem IMAP Account geschickt und sie kam an.

**Comment by gurucubano** [comment]
Ich habe nicht (untechnisch) gesagt, dass E-Mail geblockt ist, sondern das SMTP geblockt ist; machen Sie mal:

telnet smtp.1blu.de 25

das ergibt normalerweise:

telnet smtp.1blu.de 25
Trying 178.254.4.101...
Connected to smtp.1blu.de.
Escape character is '^]'.
220 ms-10.1blu.de ESMTP Exim 4.76 Tue, 01 Dec 2015 08:37:01 +0100

aus dem ffmuc aber nur 'connection refused'

einfach mal ausprobieren;

**Comment by fpletz** [comment]
Per IPv4 blockt unser VPN-Exit-Anbieter SMTP ausgehend. Das ist leider etwas unschön, dient aber der Spam-Vermeidung durch kompromittierte Client-Maschinen.

MUAs sollten nicht Port 25 sondern Port 587 (Mail Submission) zum verschicken von Mails benutzen. Siehe dazu auch https://tools.ietf.org/html/rfc6409#section-3.1.

**Comment by fpletz** [comment]
@midzer SMTP hat mit IMAP auf Netzwerk-Ebene nichts zu tun.

**Comment by midzer** [comment]
Danke für die Erläuterung @gurucubano und @fpletz 
Ich ging davon aus, dass SMTP beim Standard Mailversand (z.b. mit IMAP) verwendet wird, weil ich im Thunderbird beim Mailversand ein smtp.irgendwas server aufgerufen wird

**Comment by gurucubano** [comment]
Problem ist, auf meinem (FreeBSD) netbook wird die mail vom MUA an ein lokales sendmail uebergeben, welches sich um den Transport als MTA kuemmert und eigentlich SMTP bzw. ESMTP sprechen will...

**Comment by nickel715** [comment]
@midzer SMTP wird auch für den Mailversand genutzt, das ist schon richtig. IMAP hat mit Mailversand aber nix zu tun, IMAP wird nur für das empfangen der Mails verwendet. 
Der Knackpunkt hier ist das hier port 25 für den Versand genutzt wird (dieser ist eigtl nur für die Kommunikation von Mailserver zu Mailserver gedacht) wie von @fpletz bereits erklärt.

**Comment by fpletz** [comment]
Ich denke wir koennen das hier schliessen. Man kann in unserem Netz ein/-ausgehend ins public Internet sowieso keinen Mailserver betreiben, und das koennen wir auch nicht fixen. Per IPv6 funktionierts.
