### ISSUE TITLE
Auswahlboxen funktionieren nicht im Internet Explorer 11

### ISSUE THREAD

**Issue by midzer** [freifunkMUC/freifunkmuc.github.io#124]
Mir ist gestern aufgefallen, dass die Auswahlboxen der Firmware unter https://ffmuc.net/firmware/ im Internet Explorer nicht funktionieren.

Wär gut, wenn das noch jemand bestätigt.

**Comment by privatereese** [comment]
Kann ich bestätigen, Modell und Version gehen nicht, die erste Herstellerauswahlbox geht allerdings. Win7/ IE11.0.9600.18738

**Comment by midzer** [comment]
Danke fürs Feedback @privatereese 

Welche Fehlermeldung kommt beim Javascript?

**Comment by privatereese** [comment]
> DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
Datei: firmware

Diese Fehlermeldung kommt.

**Comment by saerdnaer** [comment]
Ich denke es ist nicht mehr notwendig in 2018 den IE11 noch zu unterstützen. Wenn dann sollte man ggf. eine Warnmeldung einbauen, um den Nutzer darauf aufmerksam zu machen einen anderen Browser zu verwenden.
