### ISSUE TITLE
Darmstädter Firmware für WR841N v10 an München anpassen

### ISSUE THREAD

**Issue by Sheep2045** [freifunkMUC/freifunkmuc.github.io#127]
Unter https://firmware.darmstadt.freifunk.net/ (Tab Experimental) haben die Darmstädter eine funktionierende Firmware für die o.g. Hardwarerevision eingestellt. Diese müßte, soweit ich es verstehe, nur noch per site.conf / site.mk an München angepaßt werden.

Das würde die Nutzung der WR841N v10 für Freifunk München ermöglichen, die zunehmend von Onlinehändlern ausgeliefert werden. Mir wurden zwei geliefert, auf die ich jetzt die Darmstädter Firmware aufgespielt habe.

**Comment by nickel715** [comment]
Es gibt doch schon ein Münchner image für den v10?

**Comment by Sheep2045** [comment]
Danke für die Info - wo finde ich das denn? Hier (https://ffmuc.net/firmware/) bin ich leider nicht fündig geworden und Google war auch nicht hilfreich (oder ich hab mich blöd angestellt).
Ein Link wäre toll, dann kann man das Ticket auch gleich wieder zumachen.

**Comment by nickel715** [comment]
Wie in Darmstadt ist es bei uns auch noch experimental: http://firmware.ffmuc.net/experimental/factory/gluon-ffmuc-v2015.7-39-g0f02267-tp-link-tl-wr841n-nd-v10.bin

**Comment by Sheep2045** [comment]
Jetzt hab ichs auch gefunden - vielen Dank! Ich dachte zuerst, daß es nur die Firmware zum Download gibt, die ich über die Auswahlboxen wählen kann - das ist ned ganz intuitiv :).
