### ISSUE TITLE
Keine Statistik

### ISSUE THREAD

**Issue by millemedium** [freifunkMUC/freifunkmuc.github.io#153]
Bei meiner Statistik https://ffmuc.net/map/#!v:m;n:18a6f7e5dfda sind seit Wochen keine echten Daten mehr zu sehen, sondern dauerhaft eine "1" bei den Clients.
Kann ich da was dagegen machen oder ist das ein Server-Problem?

**Comment by midzer** [comment]
Hi. Bitte nutz die neue Karte unter https://map.ffmuc.net/#!v:m;n:18a6f7e5dfda

**Comment by millemedium** [comment]
Super! Danke!
