### ISSUE TITLE
Redirect von alter Karte zu neuer Karte

### ISSUE THREAD

**Issue by datenhahn** [freifunkMUC/freifunkmuc.github.io#154]
Nachdem es immer wieder Leuten passiert ( z.B. #153) dass sie die alte Karte aufrufen, wäre es möglich einen redirect einzurichten? z.b. 

location /map {
return 301 https://map.ffmuc.net;
}

**Comment by fpletz** [comment]
Done. :)

**Comment by datenhahn** [comment]
nice :thumbsup:
