### ISSUE TITLE
IPv6 Subnetz beim Förderverein beantragen

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#16]
aus Techtreff-02:
IPv6 Subnetz beim Förderverein beantragen

**Comment by lhampe** [comment]
@lephisto hast du hier schon updates für uns ?

**Comment by lephisto** [comment]
Ist von meiner Seite gecancelled, weil es uns keine Rechtssicherheit bietet, und wir somit jedes x-beliebige deutsche Netz nehmen könnten. Interimslösung: V6 von Ipredator.

gruss,
Bastian

**Comment by lhampe** [comment]
w hat per Mail bestätigt - wir haben jetzt internet ;)
```
Am 25.03.2015 um 18:23 schrieb w:
>> 8. IPv6 lief bis gestern noch nicht --> ungetestet
> internet geht jetzt --> passt
```
-> close
