### ISSUE TITLE
Verbindungsprobleme IPv4 und fehlerhafte Statistik-Anzeige (Umland)

### ISSUE THREAD

**Issue by bamstam** [freifunkMUC/freifunkmuc.github.io#160]
Aktuell keine IPv4-Konnektivität im Segment Umland, fehlerhafte/fehlende Darstellung der Statistiken

**Comment by bamstam** [comment]
wieder aktuell

**Comment by fpletz** [comment]
Du kannst auch auf https://chat.ffmuc.net/ zu uns in den Chat kommen und verfolgen/melden wenn etwas nicht funktioniert.

**Comment by bamstam** [comment]
wieder aktuell, chatmeldung folgt

**Comment by bamstam** [comment]
@fpletz lassen sich github-issues in mattermost integrieren/anzeigen?

**Comment by fpletz** [comment]
Ja, aber dazu braucht man noch einen weiteren Service, der das relayed. Eigentlich waers cooler wenn man Gitlab benutzen würde, da geht das automatisch. ;)

Problem wurde mittlerweile behoben, siehe NOC Channel.

**Comment by bamstam** [comment]
wieder aktuell seit ca. 11 Uhr (Verbindungsabbrüche)

**Comment by bamstam** [comment]
tritt aktuell wieder auf, seit ca. 1 Uhr (Verbindungsabbrüche, reduzierte Geschwindigkeit)

**Comment by bamstam** [comment]
tritt aktuell wieder auf, seit ca. 16 Uhr

**Comment by bamstam** [comment]
tritt aktuell wieder auf
