### ISSUE TITLE
Toter Link zu Firmware des TP-Link TL-WA901ND v4.x

### ISSUE THREAD

**Issue by Modding** [freifunkMUC/freifunkmuc.github.io#165]
Der Link zur Firmware des TP-Link TL-WA901ND v4.x führt zu ner 404rer meldung.

https://firmware.ffmuc.net/stable/factory/gluon-ffmuc-v2016.0-tp-link-tl-wa901n-nd-v4.bin

**Comment by privatereese** [comment]
Hab den Link aus den Auswahlboxen genommen im PR #159. Die Firmware ist nicht verfügbar auf den Münchner Firmwareservern ( siehe https://firmware.ffmuc.net/stable/factory/) bei Freifunk Altdorf ist sie jedoch vorhanden (siehe http://fw1.tecff.de/stable/factory/ ), deswegen der tote Link im Auswahlmenü.
