### ISSUE TITLE
Toter Link zu TP-Link Archer FW

### ISSUE THREAD

**Issue by Nordm4nn** [freifunkMUC/freifunkmuc.github.io#168]
Hallo zusammen,
leider gehen die Downloadlinks zu den TP-Link Archer Modellen nicht.

Grüße

**Comment by krombel** [comment]
In der Zwischenzeit vllt behoben.
Sollte es immer noch nicht gehen, bitte erneut öffnen mit Links zu der genauen Seite auf der es nicht geht.
Auf firmware.ffmuc.net sollte es klappen
