### ISSUE TITLE
dezentrales dhcp (dhcpd auf knoten/router mit sync zur datenbank auf server)

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#18]
aus Techtreff-02:
dezentrales dhcp (dhcpd auf knoten/router mit sync zur datenbank auf server

**Comment by FreifunkerEZ** [comment]
wow.
gibts sowas schon? sonst ich glaub ich würde so ne art proxy bauen, der sich vom zentralen dhcpd per standard DORA eine addr geben lässt und die dann aufbewahrt (d.h. nicht verwendet sondern praktisch nur merkt) für einen zukünftigen client. und wenn dann ein client kommt würde ich den Discover abfangen und die aufbewahrte IP "weiter vererben". darauf hin würde ich mir ne neue vom master holen und wieder in meine schublade tun. das wäre für den master erstmal transparent und sau schnell. es würde für jeden proxy eine IP "eingefroren" als overhead. aber ich fürchte ich übersehe was :)
werden bei dhcp die MAC-adddrs in der db festgehalten? da würde dann natürlich der dhcp-proxy drin stehen jedes mal. macht das was aus? vielleicht gibt es eine garbage collection die bei duplicate mac sofort die alte lease frei gibt. (jeder nur ein kreuz!) was dann zu chaos führt. man könnte dem master dann sagen welche MACs von der GC auszuschließen wären. was dann nicht mehr transparent wäre.
spannend! baut mal was. ich würde gerne sehen wie profis das machen.

aha. ein anderer ansatz hier https://lists.open-mesh.org/pipermail/b.a.t.m.a.n/2011-August/005217.html
