### ISSUE TITLE
Firmware-Seite überarbeiten

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/freifunkmuc.github.io#222]
Aktuell gibt es ffmuc.net/firmware [1] und firmware.ffmuc.net [2], die den Zugriff auf die Firmware-Builds ermöglichen sollten.

Während [1] nicht mehr aktuell ist, bietet [2] nur einen einfachen Weg die factory-Images anzubieten.

Evtl. kann man etwas von anderen Communities kopieren/adaptieren. Anschließend wäre ich dafür nur eine von beiden URL's zu pflegen und die eine auf das andere weiterzuleiten.

**Comment by awlx** [comment]
Teilweise gefixt durch die letzten Commits
