### ISSUE TITLE
Knoten-Metadaten und -Graph zu LibreMap und OpenWifiMap exportieren

### ISSUE THREAD

**Issue by saerdnaer** [freifunkMUC/freifunkmuc.github.io#32]
http://libremap.net
http://openwifimap.net/

**Comment by midzer** [comment]
Gute Idee.
Die OpenWifiMap wird über https://github.com/freifunk/openwifimap-api/blob/master/API.md#pushing-nodes-into-the-database gefüttert

**Comment by fpletz** [comment]
Beide Projekte haben nicht viele Daten und scheinen eher lokale Projekte zu sein. Ich glaube der Aufwand deren API zu bedienen (und CouchDB aufzuseten) lohnt sich nicht.

Es gibt http://www.freifunk-karte.de/, die das nodelist Format nehmen und die URLs aus der freifunk.net API holen. Dort sind wir auch vertreten.
