### ISSUE TITLE
[Flyer, etc.] Einheitliches Logo/Design wählen + zentrales Set an Infomaterial erstellen

### ISSUE THREAD

**Issue by spoonicorn** [freifunkMUC/freifunkmuc.github.io#34]
Auch für die kommenden öffentlichen Veranstaltungen jetzt konkret wichtig. Wir sollten uns (zumindest vorrübergehend) auf ein Design/Logo einigen und was für Material benötigt wird (Flyer, Plakate, etc.) . Wir brauchen ein paar Tage Vorlauf wegen Druck.

**Comment by MartinDesigner** [comment]
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
