### ISSUE TITLE
Veraltete Links zu App (Hopp Foundation & alte FFMeet Client Versionen)

### ISSUE THREAD

**Issue by rocket-plane** [freifunkMUC/freifunkmuc.github.io#345]
Der Link für die Android und iOS Apps auf der Hauptseite
[https://meet.ffmuc.net/](https://meet.ffmuc.net/) 
führen leider ins leere, da die App "Digitales Klassenzimmer" scheinbar nicht mehr verfügbar ist.

**Comment by T0biii** [comment]
Leider hat Hopp Foundation die App "digitales klassenzimmer" eingestellt.
@GoliathLabs oder @krombel könnt ihr die Links auf Jitsi direkt anpassen oder entfernen?
Bei F-Droid ist es bereits auf Jitsi eingestellt.

**Comment by GoliathLabs** [comment]
Das müsste vmtl. @krombel machen.

**Comment by T0biii** [comment]
wie es aussieht wurden die links für AppStore, GooglePlayStore sowie F-Droid entfernt (lediglich die Bilder sind übrig)
Die Links zur Windows App, macOSApp sowie LinuxApp scheinen zu funktionieren.
