### ISSUE TITLE
DNSCrypt-Server geht nicht

### ISSUE THREAD

**Issue by overbrain74** [freifunkMUC/freifunkmuc.github.io#354]
Hallo Freifunker,

wie ich eben feststellte, geht der IPv4 DNSCrypt-Server nicht.
DNS Stamp: sdns://AQcAAAAAAAAADzUuMS42Ni4yNTU6ODQ0MyAH0Hrxz9xdmXadPwJmkKcESWXCdCdseRyu9a7zuQxG-hkyLmRuc2NyeXB0LWNlcnQuZmZtdWMubmV0
Ich nutze Eure DNS-Server in AdGuard Home v0.107.32.

Beste Grüße

**Comment by T0biii** [comment]
Hey @overbrain74, 
melde dich doch am besten unkompliziert über den [chat](https://chat.ffmuc.net) bei uns, falls das Problem weiterhin besteht.
Oder per Mail E-Mail: [hilfe@ffmuc.bayern](mailto:hilfe@ffmuc.bayern) oder Web: [tickets.ffmuc.net](https://tickets.ffmuc.net/)
