### ISSUE TITLE
Anleitung fuers aufsetzen von Gateway und IC-VPN ins ffmuc Wiki

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#39]
aus Techtreff-03:
"mephisto hat das aufsetzen seiner Gateways in nem Pad prokolliert und macht da ne Wikiseite draus
http://pad.freifunk.net/p/muc-gwinstallation
http://pad.freifunk.net/p/muc-icvpn"

**Comment by fpletz** [comment]
Ist nicht mehr relevant, da alles in https://github.com/freifunkMUC/puppet-ffm in Code abgebildet ist/wird.
