### ISSUE TITLE
[Twitter] Besseres Bild für Header

### ISSUE THREAD

**Issue by midzer** [freifunkMUC/freifunkmuc.github.io#4]
Auf meinem Screen macht der Header vom FreifunkMUC Twitter Account einen recht stark verpixelten Eindruck.

Vielleicht stolpert jemand über eine höher aufgelöste gute Aufnahme der Münchner Skyline oder man verwendet einen der bisherigen Logoentwürfe ausm Wiki.

Optimal sind Bilder mit 1500x500 (maximum für den Header bei Twitter)

**Comment by midzer** [comment]
@chris007de ich schlage vor folgendes Bild zu verwenden:
https://github.com/freifunkMUC/logo_merchandise_ci/blob/master/twitter/Munich_skyline_1_1500x500.jpg

Original ist von http://commons.wikimedia.org/wiki/File:Munich_skyline_1.jpg
Bitte den Author in einem Tweet wegen CC-SA-3.0 erwähnen vgl. https://twitter.com/wikicommons/status/458770476009943040

**Comment by chris007de** [comment]
fixed \o/
