### ISSUE TITLE
Erstellen eines Standard-Schluessel-Pull-Scripts fuer Gateways

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#40]
Erstellen eines Scripts, durch einen Cronjob aufgerufen werden kann und damit periodisch die fastd-Keys aus dem Schluesselrepo holt.
Sollte robust gegen gefailte git pulls sein (z.B. wegkopieren des vorhandenen Schluesselverzeichnisses und zurueckkopieren der alten Schluessel falls der git pull fehlschlaegt)

**Comment by saerdnaer** [comment]
Hat sich das Issue inzwischen wegen Umstellung von White- auf Blacklist erledigt?

**Comment by fpletz** [comment]
Man müsste jetzt halt eine Blacklist statt einer Whitelist pullen…

**Comment by krombel** [comment]
Dies wird in Zukunft über salt geregelt
