### ISSUE TITLE
DNS records unter '<node>.node.ffmuc.net' kaputt

### ISSUE THREAD

**Issue by henning-schild** [freifunkMUC/freifunkmuc.github.io#454]
In der Node-Ansicht von stats.ffmuc.net ist oben rechts im dashboard ein link zu "Node Status Page". Der geht aber leider nicht weil das DNS dahinter immer auf "127.0.0.1" bzw "::1" auflöst. Das habe ich sowohl aus dem Internet als auch aus dem Freifunknetz probiert.

Vermutlich sollte man da nur AAAA bekommen und dabei die öffentlichen Adressen die auch auf der Karte angezeigt werden.

Früher hatte ich meine Nodes mal in meiner .ssh/config als Hosts stehen über irgendwelche Namen die auch aus dem Internet gingen. Aber das geht schon ein paar Jahre nicht mehr. Vielleicht war es am Ende das.

Man sollte wohl entweder das dynamische DNS fixen oder die Links aus den dashboards nehmen. Oder vielleicht gibts ja solche Namen aber die links sind irgendwie veraltet. Ich persönlich fände Namen praktisch zB für ssh.

Bsp:

- https://stats.ffmuc.net/d/hRIn3dRWk/mesh-nodes?orgId=1&var-nodeid=f09fc26116f5&refresh=1m
   - [Node Status Page](http://f09fc26116f5.node.ffmuc.net/) link aus der Seite geht nicht

```
$ dig f09fc26116f5.node.ffmuc.net AAAA +short
::1
$ dig f09fc26116f5.node.ffmuc.net A +short
127.0.0.1
```

**Comment by T0biii** [comment]
Leider ist das Feature nicht oder nicht mehr implementiert bei uns. Wir hatten dazu auch das ein oder andere Gespräch bei im https://chat.ffmuc.net aber bis jetzt hat sich niemand gefunden der dies wieder implementiert.
Ich gebe die Info weiter das wir das ggf. aus dem Grafana Dashboard rausnehmen.

**Comment by T0biii** [comment]
für Testing purpose ich habe das mal auf einen meiner Server eingerichtet:
https://github.com/T0biii/yanicOutputToZonefile
und ein cron job der alle 5 min das Python ausführt und dann den bind Container neu startet

http://f09fc26116f5.ffmuc.t0biii.de
löst auf die beiden IPv6 Adressen auf 
```sh
Name:    f09fc26116f5.ffmuc.t0biii.de
Addresses:  2001:678:ed0:100:f29f:c2ff:fe61:16f5
          2001:678:e68:100:f29f:c2ff:fe61:16f5
```

und 
http://neuhauser.ffmuc.t0biii.de 
ist ein cname von f09fc26116f5
```sh
Name:    f09fc26116f5.ffmuc.t0biii.de
Addresses:  2001:678:ed0:100:f29f:c2ff:fe61:16f5
          2001:678:e68:100:f29f:c2ff:fe61:16f5
Aliases:  neuhauser.ffmuc.t0biii.de
```

Also wenn man einen bind Server hat kann man dort sich eine neue Zone für alle Nodes anlegen und dann hat man DNS für alle node hostname (und ggf. node-id)

**Comment by henning-schild** [comment]
Den Dienst konnte ich jetzt sogar auch verwenden, aber solange er so wenig offiziell daherkommt werde ich ihn nicht hernehmen.

Statt eine website zu parsen sollte man sowas wohl tiefer im Backend machen, da müssten die Daten ja direkt vorliegen. Oder mit https://github.com/openwrt/packages/tree/master/net/ddns-scripts verteilt auf den Nodes, dazu braucht man aber auch so einen DynDNS server.

Die Idee das DNS nochmal anzugehen sollte aber vielleicht eher in einem neuen Issue stehen. Ich fände es gut und würde es für ssh und die Knotenwebsite gerne verwenden. Aber wichtig ist es mir nicht, zumindest ist jetzt mal der tote Link weg.

**Comment by T0biii** [comment]
der "Dienst" ist auch nur für Test purpose und soll auch nicht verwendet werden.

die Daten liegen in der https://map.ffmuc.net/data/meshviewer.json vor somit wird hier keine Webseite geparst, diese Datei wird von unserem yanic erstellt und ist eine tiefliegende Service, worauf mehreren stellen aufbauen wie z.B. die map 

Um sowas einzubauen könnte ggf. jemand der Ahnung hat dies in unserem salt Repo einbauen  
https://github.com/freifunkMUC/ffmuc-salt-public
Aber dafür müsste jemand gefunden werden der dieses tut und da sehe ich momentan niemanden der dies macht.


das von dir erwähnte package könnte ggf. von dir selber nach installiert werden:
https://openwrt.org/docs/guide-user/services/ddns/client#command-line_instructions
(könnte aber gut sein das nach jedem Firmware Update das package erneut installiert werden muss)
