### ISSUE TITLE
Zugang ueber Telnet auf Nodes ohne Passwort/SSH Key unterbinden

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#48]
Zur Zeit ist es moeglich, auf Nodes bei denen kein Passwort oder SSH Key im Expert Modus konfiguriert wurde, ohne Passwort ueber Telnet auf das Geraet zu kommen.

Loesungsvorschlag von ruebe:
telnetd deaktivieren.

**Comment by fpletz** [comment]
Wurde hier gefixt: https://github.com/freifunk-gluon/gluon/commit/111cf1268aaac76892e7342c1a354ef27793edd4
