### ISSUE TITLE
Übergangsplanung Testbetrieb -> Stable

### ISSUE THREAD

**Issue by andz82** [freifunkMUC/freifunkmuc.github.io#52]
Ich habe dazu auch schon mit fpletz gesprochen:

Wenn wir einen harten Umstieg machen, wobei auch die Firmware geändert werden muss (vgl. Kanalwechsel, neues batman etc.) ist folgendes Vorgehen Sinnvoll:

T-2 bis 4 Wochen: HInweis auf der Startseite, im IRC, auf der Liste dass der Testbetrieb bald beendet wird mit der Folge, dass alle Nodebetreiber welche kein Autoupdate aktiviert haben, manuell zum Stichtag umstellen müssen (incl Noob-Anleitung)
T-2 Wochen: Bereitstellen der "Stable" Gateways und ausgiebiger Test der neuen FFMuc Firmware
T-5: Tage: Nochmals Hinweis per Mailingliste und auf Homepage
T-0 Tage: Verteilen der neuen Firmware per Autoupdate. Autupdate sollte in der Enduser-Stable Firmware standardmäßgi aktiviert sein.

Ab diesem Zeitpunkt ist FFMuc in 2 Netze unterteilt. 
Ein Testing-Netz (mit z.B. 1-2 Gateways), in welchem sich dann auch noch alle Knoten mit der alten Firmware befinden. Dieses kann weiterhin aufrecht erhalten werden um genau den genannten Zweck zu erfüllen, nämlich Testing für was auch immer (neue GW config, neue Firmware...). Kann auch auf Kanal 1 bleiben. Muss auch keinen VPN Tunnel ins "echte" Internet haben.

Ein öffentliches stable-Netz welches mit 2-3 Gateways mit stabiler config arbeitet und in der Öffentlichkeit (Karte etc.) das einzige wahrgenommene sein soll.

**Comment by jibijay** [comment]
Ich schlage vor, die vorgeschlagene Uebergangsplanung im liquidfeedback zur Abstimmung zu stellen.

**Comment by markus2342** [comment]
Produktivbetrieb ist aktiv.
Siehe https://ffmuc.net/testbetrieb/freifunkmuc/2015/03/12/netzupgrade/ .
