### ISSUE TITLE
Wording Mesh-VPN im Config-Modus

### ISSUE THREAD

**Issue by fpletz** [freifunkMUC/freifunkmuc.github.io#59]
Im Config-Modus kann man das "Mesh-VPN" aktivieren. Für einen normalen Nutzer ist das aber unverständlich. Wir sollten den Punkt in "Internetverbindung teilen" oder ähnlich umbenennen und technisches Wording und Erläuterungen auf die Beschreibung beschränken.

**Comment by midzer** [comment]
Kann mir gut vorstellen, dass manche mit Mesh-VPN nix anfangen können und den Haken dann nicht setzen.
Bis sie dann merken, dass ihre Insel keine Verbindung zu den Gateways aufbaut.
Finde "Internetverbindung teilen" gut.
+1
