### ISSUE TITLE
dns reverse einrichten (intern ffm.)

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/freifunkmuc.github.io#64]
es sollte im internen dns nicht nur die forward zone(n)
ffm.
sonden auch die entsprechenden reverse zonen eingerichtet werden.
also diese zonen:
0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa.
80.10.in-addr.arpa.

habs mal zur probe hier so gemacht:

nslookup - s.pacher.com.

> ls -d ffm.
> [UnKnown]
>  ffm.                           SOA    gw04.ffm mephisto.mephis.to. (2002082732 86400 7200 3600000 86400)
>  ffm.                           NS     gw01.ffm
>  ffm.                           NS     gw02.ffm
>  ffm.                           NS     gw03.ffm
>  ffm.                           NS     gw04.ffm
>  answer.ffm.                    AAAA   fdef:ffc0:4fff:0:f005:2fff:fe6a:affa
>  gw01.ffm.                      A      10.80.0.11
>  gw01.ffm.                      AAAA   fdef:ffc0:4fff::11
>  gw02.ffm.                      A      10.80.0.12
>  gw02.ffm.                      AAAA   fdef:ffc0:4fff::12
>  gw03.ffm.                      A      10.80.0.13
>  gw03.ffm.                      AAAA   fdef:ffc0:4fff::13
>  gw04.ffm.                      A      10.80.0.14
>  gw04.ffm.                      AAAA   fdef:ffc0:4fff::14
>  mini.ffm.                      CNAME  minime.ffm
>  minime.ffm.                    AAAA   fdef:ffc0:4fff:0:240:48ff:feb1:b57f
>  firmware.services.ffm.         AAAA   fdef:ffc0:4fff::11
>  firmware.services.ffm.         AAAA   fdef:ffc0:4fff::66
>  1.ntp.services.ffm.            A      10.80.0.11
>  1.ntp.services.ffm.            AAAA   fdef:ffc0:4fff::11
>  2.ntp.services.ffm.            A      10.80.0.12
>  2.ntp.services.ffm.            AAAA   fdef:ffc0:4fff::12
>  3.ntp.services.ffm.            A      10.80.0.13
>  3.ntp.services.ffm.            AAAA   fdef:ffc0:4fff::13
>  4.ntp.services.ffm.            A      10.80.0.14
>  4.ntp.services.ffm.            AAAA   fdef:ffc0:4fff::14
>  srv01.ffm.                     A      10.80.0.15
>  srv01.ffm.                     AAAA   fdef:ffc0:4fff::15
>  ffm.                           SOA    gw04.ffm mephisto.mephis.to. (2002082732 86400 7200 3600000 86400)
> 
> ls -d ffm.freifunk.cf.
> [UnKnown]
>  ffm.freifunk.cf.               SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111802 14400 3600 1209600 600)
>  ffm.freifunk.cf.               NS     sedna.space.pacher.com
>  answer.ffm.freifunk.cf.        AAAA   fdef:ffc0:4fff:0:f005:2fff:fe6a:affa
>  fpletz-srv.ffm.freifunk.cf.    A      10.80.0.130
>  gw01.ffm.freifunk.cf.          A      10.80.0.11
>  gw01.ffm.freifunk.cf.          AAAA   fdef:ffc0:4fff::11
>  gw02.ffm.freifunk.cf.          A      10.80.0.12
>  gw02.ffm.freifunk.cf.          AAAA   fdef:ffc0:4fff::12
>  gw03.ffm.freifunk.cf.          A      10.80.0.13
>  gw03.ffm.freifunk.cf.          AAAA   fdef:ffc0:4fff::13
>  gw04.ffm.freifunk.cf.          A      10.80.0.14
>  gw04.ffm.freifunk.cf.          AAAA   fdef:ffc0:4fff::14
>  mini.ffm.freifunk.cf.          CNAME  minimi.ffm.freifunk.cf
>  minimi.ffm.freifunk.cf.        AAAA   fdef:ffc0:4fff:0:240:48ff:feb1:b57f
>  firmware.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::11
>  firmware.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::66
>  1.ntp.services.ffm.freifunk.cf. A      10.80.0.11
>  1.ntp.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::11
>  2.ntp.services.ffm.freifunk.cf. A      10.80.0.12
>  2.ntp.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::12
>  3.ntp.services.ffm.freifunk.cf. A      10.80.0.13
>  3.ntp.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::13
>  4.ntp.services.ffm.freifunk.cf. A      10.80.0.14
>  4.ntp.services.ffm.freifunk.cf. AAAA   fdef:ffc0:4fff::14
>  srv01.ffm.freifunk.cf.         AAAA   fdef:ffc0:4fff::129
>  srv01.ffm.freifunk.cf.         A      10.80.0.129
>  ffm.freifunk.cf.               SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111802 14400 3600 1209600 600)
> 
> ls -d 0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa.
> [UnKnown]
>  0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111803 14400 3600 1209600 600)
>  0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. NS     sedna.space.pacher.com
>  1.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    gw01.ffm.freifunk.cf
>  2.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    gw02.ffm.freifunk.cf
>  3.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    gw03.ffm.freifunk.cf
>  4.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    gw04.ffm.freifunk.cf
>  6.6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    firmware.services.ffm.freifunk.cf
>  9.2.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    srv01.ffm.freifunk.cf
>  f.7.5.b.1.b.e.f.f.f.8.4.0.4.2.0.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    minimi.ffm.freifunk.cf
>  a.f.f.a.a.6.e.f.f.f.f.2.5.0.0.f.0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. PTR    answer.ffm.freifunk.cf
>  0.0.0.0.f.f.f.4.0.c.f.f.f.e.d.f.ip6.arpa. SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111803 14400 3600 1209600 600)
> 
> ls -d 80.10.in-addr.arpa.
> [UnKnown]
>  80.10.in-addr.arpa.            SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111808 14400 3600 1209600 600)
>  80.10.in-addr.arpa.            NS     sedna.space.pacher.com
>  11.0.80.10.in-addr.arpa.       PTR    gw01.ffm.freifunk.cf
>  12.0.80.10.in-addr.arpa.       PTR    gw02.ffm.freifunk.cf
>  129.0.80.10.in-addr.arpa.      PTR    srv01.ffm.freifunk.cf
>  13.0.80.10.in-addr.arpa.       PTR    gw03.ffm.freifunk.cf
>  130.0.80.10.in-addr.arpa.      PTR    fpletz-srv.ffm.freifunk.cf
>  14.0.80.10.in-addr.arpa.       PTR    gw04.ffm.freifunk.cf
>  80.10.in-addr.arpa.            SOA    sedna.space.pacher.com root.sedna.space.pacher.com. (2014111808 14400 3600 1209600 600)

ich bitte das angehängte ".freifunk.cf." zu "entschuldigen".
und auch die fehlenden(/falschen) "ns" einträge!

**Comment by krombel** [comment]
ffm. als interne Domain wird nicht weiter benutzt.
Sehe dies also als "Relikt alter Zeiten"
