### ISSUE TITLE
Unklarer Status der Autoupdate Funktion im luci

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#65]
Die Autoupdate Funktionalitaet sollte seit 0.6~stable20141018 standardmaessig aktiviert sein.
Geht man allerdings im gluon luci auf die Expertenseite, so ist die Checkbox dafuer unchecked.

Ist dies nur ein Darstellungsproblem?
Sollte man die Autoupdate Checkbox nicht sowieso auf die normale Wizard Page umziehen?

**Comment by jibijay** [comment]
Wie ist da der aktuelle Status?

**Comment by fpletz** [comment]
Das Ticket wird in freifunkMUC/site-ffm#6 bearbeitet.
