### ISSUE TITLE
Ueberarbeitung der Aufteilung der Optionen im luci

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#66]
Ich stelle zur Debatte, die Aufteilung der Optionen im luci in den Wizard und Expertenbereich zu ueberdenken.

Meine Vorschlaege:
- Passwort/SSH auf Wizard
- Bandbreitenbegrenzung auf Expert

**Comment by midzer** [comment]
Ich sehe keinen Grund das Passwort setzen in der Hauptseite unterzubringen.
Nur fortgeschrittene Anwender wollen sich imo per SSH auf den eigenen Router aufschalten und müssen dafür ein Passwort setzen.
Gerade die (für Unbedarfte unnötige) Auswahl eine Passworts überfordert viele Endanwender...sofern sie nicht ihr Standardpasswort verwenden.

Bandbreitenbegrenzung dagegen sehe ich auch in den Experteneinstellungen.
Gerade für schwach angebundene Punkte ist eine Begrenzung oft erforderlich, damit regulärer Traffic nicht ausgebremst werden kann bzw immer Kapazitäten dafür da sind.

**Comment by krombel** [comment]
Wird mittlerweile im "Standard-Gluon" umgesetzt
