### ISSUE TITLE
 snapshot~20141119 auf TP-Link 841NDv8: Darstellung im Knotengraph

### ISSUE THREAD

**Issue by bamstam** [freifunkMUC/freifunkmuc.github.io#69]
Nach dem Flashen von snapshot~20141119 auf einem TP-Link 841NDv8:

- Knoten wird im Knotengraph nicht mit dem im Setup eingetragenen Knotennamen, sondern mit einem Teil der MAC-Adresse angezeigt
- Knoten wird als "ohne Gluon" (ohne grünen Ring) angezeigt
- zusätzlich ist dauerhaft ein mittelgroßer grüner Punkt mit blauem Kern (kein Client) mit dem Knoten verbunden
- (Knoten wird nicht in der Knotenliste angezeigt) wird doch angezeigt, die Felder Firmware und Modell sind jedoch leer

(Zurückflashen auf gluon-ffm-stable~20141018: Knoten wird wieder korrekt im Knotengraph dargestellt)

**Comment by chris007de** [comment]
Der Vollstaendigkeit/Archivierung halber hier noch die Mail von @messimuc kuerzlich auf Muenchen-dev:

"mein Knoten montgelas-17-pizza ist ja in der Liste bisher immer als
„MAC-Adresse“ in der Knotenliste aufgetaucht, ganz normal installiert:
TP-Link TL-WR841N/ND v8 mit snapshot~20141119
 - Davon habe ich mit die uci - Daten geholt (hängt an)

Auf ffm-0.6~stable20141018 downgegraded (da stimmt die anzeige in der
Knotenliste)
 - Auch davon die uci - Daten geholt (hängt an)

und verglichen (ohne das ich weiß was ich tue)

Dann wieder upgrade auf snapshot~20141119 und folgende Werte aus der
ffm-0.6~stable20141018 übernommen:

uci set network.mesh_vpn.macaddr='12:fe:ed:ec:99:b4’		(war 12:02:ed:eb:99:b4)
uci delete wireless.client_radio0.macaddr					(war 12:00:ee:eb:99:b4)
uci delete wireless.mesh_radio0.macaddr					(war 12:01:ee:eb:99:b4)
uci commit
reboot 

JETZT GEHTS: montgelas-17-pizza erscheint mit seinem Namen in der Knotenliste und
tut wie es scheint seinen Dienst."

**Comment by FRNK-BK** [comment]
Workaround (mit angepasster MAC) hat auf v2015.1 scheinbar funktioniert. Auch hier ne 12er MAC.
Danke.

**Comment by messimuc** [comment]
Auf https://forum.freifunk.net/t/router-wird-als-client-auf-der-map-angezeigt/2266/15
haben auch andere Communitys das Problem durchgehechelt.

Mit der neueren **nodedb.py** aus der aktuellen Version des ffmap-backend gibt es das Problem wohl nicht.
(ungeprüft - copy&paste)

ffmap-backend macht ole ? Ich assigne mal.

Für den Fall, das beheben noch dauert, es reicht die beiden Wireless-MACs zu löschen, mesh_vpn.macaddr kann bleiben (macht den Workaround universeller), also so:

`uci delete wireless.client_radio0.macaddr`
`uci delete wireless.mesh_radio0.macaddr`
`uci commit`
`reboot`

**Comment by chris007de** [comment]
Sollte dank @t-offline's patch gefixt sein (https://github.com/freifunkMUC/ffmap-backend/commit/1aeea4410d92f8f1d3b6deb16759c1b310e1ce20)

Erstmal closed
