### ISSUE TITLE
Bitte zusätzlichen Link zu: http://37.120.168.150/firmware/stable/ in die Webseite einbauen.

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/freifunkmuc.github.io#70]
Hallo,

bitte den Link: http://37.120.168.150/firmware/stable/
(besser noch mit DNS FQDN)
irgendwo auf die Webseite:
http://freifunk-muenchen.de/firmware/
unterbringen.
Damit kann man auch leicht auf andere ff Versionen umsteigen.
Danke.

**Comment by T0biii** [comment]
Close? Seite ist nicht mehr erreichbar!

**Comment by krombel** [comment]
Danke für den Hinweis.
Aktuell sind die Firmware-Builds über https://firmware.ffmuc.net abrufbar
