### ISSUE TITLE
Verbindungsaufbau mit Android-Devices

### ISSUE THREAD

**Issue by bamstam** [freifunkMUC/freifunkmuc.github.io#73]
Android 4.2.1: Freifunk-Netz wird nicht als unverschlüsseltes Netzwerk angezeigt, beim Verbindungsaufbau wird ein Passwort verlangt (siehe Diskussion Mailingliste 27.11.2014)

Vergleichstest:
Android 2.3.5: Korrekte Anzeige des Freifunk-Netzes als unverschlüsseltes Netzwerk, keine Passwortabfrage, Login und Internetzugang problemlos möglich

**Comment by midzer** [comment]
Mit Android 4.2.2 funktioniert es reibungslos

**Comment by krombel** [comment]
nicht mehr relevant
