### ISSUE TITLE
Mehr Infos beim keyformular anzeigen nach erfolgreicher Eintragung

### ISSUE THREAD

**Issue by jibijay** [freifunkMUC/freifunkmuc.github.io#76]
Unbedarfter Benutzer traegt key ein und kriegt dann eine kryptische seite. Hier waere eine Weiterleitung auf eine statische Seite oder ein Erklaertext besser.

**Comment by fpletz** [comment]
Es wird kein Keyformular mehr geben, da wir zukünftig Blacklisting machen, siehe [i124](https://lqfb.freifunk-muenchen.de/lf/initiative/show/124.html).
