### ISSUE TITLE
Community Server Puppet: Softwareauswahl

### ISSUE THREAD

**Issue by spoonicorn** [freifunkMUC/freifunkmuc.github.io#78]
== Webseite ==
1:1 Übernahme der bestehenden Page (jekyll heißt der markdown transformator, den Github nutzt)
http://jekyllrb.com/docs/installation/
Software: Nginx

== Wiki ==
Mediawiki/Dokuwiki/?

== Mailinglisten ==
Software: mailman + postfix + nginx
https://www.howtoforge.com/running-mailman-on-nginx-lemp-on-debian-squeeze-ubuntu-11.04-11.10
https://black-pixel.net/mailman-with-postfix-and-nginx-on-centos-6.html

== Support ==
OTRS (nginx + perl + mysql)
http://www.haschmi.de/otrs-on-nginx/

== Backup ==
backup2l (einfach, kann encrypted backups)
http://backup2l.sourceforge.net/
Kann man dann auf ein beliebiges Storage syncen. Kann vorerst meinen vserver als backup zur Verfügung stellen

**Comment by saerdnaer** [comment]
Gibts irgendwo eine Schriftliche Begründung warum man jetzt nochmal ein neues Wiki und Mailinglisten-Server aufsetzen muss?

**Comment by fpletz** [comment]
@saerdnaer Nein. Mindestens der Verein braucht eine eigene Infrastruktur was Mail/Mailinglisten angeht. Github ist als Wiki nicht wirklich benutzbar.

**Comment by saerdnaer** [comment]
Okay, danke für die Erklärung.

**Comment by krombel** [comment]
Scheint mitterweile erledigt oder nicht mehr relevant zu sein.
