### ISSUE TITLE
Bitte noch mal den Kanalwechsel überdenken

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/freifunkmuc.github.io#81]
Hallo zusammen,

wir haben zwar in https://lqfb.freifunk-muenchen.de/lf/initiative/show/113.html bei 9 Stimmen Wahlbeteiligung mit 7 gegen 2 Stimmen den Wechsel von Kanal 1 auf Kanal 6 abgestimmt, dennoch bleiben bei mir große Zweifel ob das sinnvoll ist. Meine Gründe sind bereits vorgetragen.

Zusätzlich habe ich mir mal 40 "site.conf" angesehen und dabei gefunden, dass 24 davon auf Kanal 1
eingestellt sind. Nur 3 haben sich für Kanal 6 entschieden.

Bitte, bitte denkt noch mal darüber nach.
Danke.

Servus
Christian

**Comment by fpletz** [comment]
Geht nur per LQFB.

**Comment by t-offline** [comment]
Wann darf ich hier was sagen, wann auf lqfb?
Welche Entscheidungen werden wo gefällt?
Hier wurde doch auch viel entschieden bzw einfach gemacht...
Klar, ein Kanalwechsel zieht derart große Änderungen nach sich, da sollten schon viele drüber nachdenken und dann entscheiden. Ich jedenfalls habe ein riesen Problem mit dem beabsichtigten Wechsel vom Kanal 1 zum Kanal 6. Verstehen kann ich es nicht, warum dass gemacht werden soll.

Servus
Christian

P.S.
Ich möchte immer noch gerne "mitspielen"

**Comment by fpletz** [comment]
Schon, aber wir haben eine Entscheidung im LQFB getroffen, deswegen sollten wir sie nicht einfach so ignorieren. Du darfst "mitspielen", aber die Mehrheit war halt für Kanal 6.
