### ISSUE TITLE
Warnhinweis "Kontaktadresse auf map.freifunk-muenchen.de Sichtbar" in luci einbauen

### ISSUE THREAD

**Issue by lhampe** [freifunkMUC/freifunkmuc.github.io#82]
Da wir zukünftig die Kontaktadresse / E-Mail unter http://map.freifunk-muenchen.de/list.html anzeigen, sollten wir einen Hinweis auch in die Config GUI einbauen.

**Comment by fpletz** [comment]
Es gibt dafür bereits einen Issue im Firmware-Repo: https://github.com/freifunkMUC/site-ffm/issues/12
