### ISSUE TITLE
Das liquid feedback verschickt nicht funktionierende Links

### ISSUE THREAD

**Issue by ajs124** [freifunkMUC/freifunkmuc.github.io#87]
Hey,

keine Ahnung ob das hier die richtige Anlaufstelle ist, aber eure Liquid feedback Instanz hat mir Zwecks der Registrierung 1. das hier

```
Hallo

Du bist zu LiquidFeedback eingeladen. Bitte klicke auf den folgenden Link, um dich zu registrieren:

https://lqfb.freifunk-muenchen.de/lf/index/register.html?invite=invite

Sollte der Link nicht funktionieren, öffne bitte die folgenden URL in Deinem Web-Browser:

/lf/index/register.html
[…]
```

(fehlendes Protokoll + Domain) und 2. das hier

```
[…]
Bitte bestätige Deine E-Mail-Adresse durch Klick auf folgenden Link:

https://lqfb.freifunk-muenchen.de//lf/index/confirm_notify_email.html?secret=secret

Sollte der Link nicht funktionieren, öffne bitte die folgenden URL in Deinem Web-Browser:

https://lqfb.freifunk-muenchen.de//lf/index/confirm_notify_email.html

Auf dieser Seite gib bitten den folgenden Code ein:
[…]
```

(doppelter / → 404) gemailt.

Das ist natürlich für quasi jeden zu überwinden, aber toll ist es trotz dem nicht.

**Comment by midzer** [comment]
Ich bekam eine korrekte Mail an meine eMail-Adresse.
Mit Klick auf den Link konnte ich den Registrierungsvorgang starten.

> Du bist zu LiquidFeedback eingeladen. Bitte klicke auf den folgenden Link, um dich zu registrieren:

> https://lqfb.freifunk-muenchen.de/lf/index/register.html?invite=passphrase

> Sollte der Link nicht funktionieren, öffne bitte die folgenden URL in Deinem Web-Browser:

> /lf/index/register.html

> Auf dieser Seite gib den folgenden Code ein:

> passphrase

**Comment by ajs124** [comment]
Jo, der 1. link tut und ich hab mich auch registriert und meine E-Mail verifiziert, aber der 2. ist keine URL und die links zur E-Mail Verifikation funktioniert nur wenn man einen der beiden "/" nach der Domain entfernt.

Am 28. April 2015 00:44:03 MESZ, schrieb midzer <notifications@github.com>:
