### ISSUE TITLE
Statement zu deutscher Exit-IP auf Website/FAQ

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#92]
Da immer wieder mal (nicht häufig, aber immerhin) Verwirrung bzgl. deutscher Exit-IP über Leaseweb aufkommt, ist es angemessen die Nutzer proaktiv über dieses Setup zu informieren; v.A. da von uns/Freifunk im Allgemeinen ja eigentlich immer das "Schweden-VPN" propagiert wird.

@fpletz da Du das eingerichtet hast, hättest Du da Lust/Zeit mal kurz was zu schreiben?

**Comment by fpletz** [comment]
Um Verwirrung zu vermeiden habe ich vorhin den AirVPN Exit von gw03 auf die Niederlande umgeschwenkt. So kann man von "Auslands-VPN" sprechen. Ich schreibe dazu was auf die Webseite bzw. in die FAQs.
