### ISSUE TITLE
Automatisches Abschalten der SSID wenn kein Internet vorhanden

### ISSUE THREAD

**Issue by RiBro** [freifunkMUC/freifunkmuc.github.io#93]
Ein Knoten ohne Verbindung zu einen Gateway ist schlecht für den Ruf von freifunk, da ein normaler 
User mit so einen Hotspot nichts anfangen kann.
Ein Knoten, welcher kein Zugang zum Internet hat, sollte die Client SSID abschalten oder ändern.

Ein Vorschlag wäre die Anzahl der im BATMAN Netz verfügbaren Knoten als Metrik zu nehmen.

```
#! /bin/ash

NODECOUNT=$(batctl -m bat0 o | wc -l)

if ( [ "$NODECOUNT" -gt "100" ] )
then
   if ( [ "$(uci get wireless.client_radio0.disabled)" -eq "1"  ] )
   then
       uci set wireless.client_radio0.disabled=0
       uci set wireless.radio0.disabled=0
       wifi
   fi
else
   uci set wireless.client_radio0.disabled=1
   uci set wireless.radio0.disabled=0
   wifi

fi
```

**Comment by fpletz** [comment]
Das ist meiner Meinung nach keine gute Idee. Es kann auch Sinn machen Freifunk ohne Internetanbindung zu betreiben. Wir sollten in dem Fall eher eine Landing-Page mit Informationen ausliefern anstatt das Wifi abzuschalten.

**Comment by RiBro** [comment]
Landing Page finde ich in den Fall auch gut. Der Nutzer sollte sich halt nicht ärgern.
Die Frage ist nur wie man das macht, wenn auf den Knoten "noch" kein DHCP bzw. DNS Server läuft.

**Comment by fpletz** [comment]
Das ist korrekt. :) Wir wollten da noch einige Umbauten machen damit alle Nodes DHCP und DNS machen, was auch für unsere zukünftige Netzwerkarchitektur wie in https://github.com/freifunkMUC/freifunkmuc.github.io/wiki/Mesh-of-Meshes:-tinc-&-batman beschrieben notwendig wäre.

**Comment by RiBro** [comment]
Mit Mesh of Meshes funktioniert auch oben genanntes Skript nicht mehr. Dann muss man direkt die GW Verbindung prüfen...
