### ISSUE TITLE
Nachbarschaftsflyer, Druckvorlagen für Sticker auf Website

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#94]
Aktuell sind die Druckvorlagen für Flyer, Sticker, Poster etc. nur unter https://github.com/freifunkMUC/logo_merchandise_ci zu erreichen.
Man sollte um die Zugangsbarriere zu senken, ausgewählte Vorlagen als PDF auf der Homepage direkt verlinkt als Download anbieten.

Meinungen, Vorschläge dazu?

**Comment by midzer** [comment]
Im Club waren zumindest vor 2 Monaten noch genug Flyer vorhanden.
Wie es mit Sticker ausschaut, weiß ich nicht.

Klar, schaden kanns nicht ausgewählte Inhalte auf der Webseite unterzubringen.
Vielleicht eine Kategorie unter Mitmachen->Spread the word oder so ähnlich^^

**Comment by hexadezimalion** [comment]
Finde ich auch gut!

**Comment by b0-ris** [comment]
Ich schlage dieses PDF vor:
https://github.com/freifunkMUC/logo_merchandise_ci/blob/master/flyer/flyer_freifunk_muenchen.pdf

**Comment by hexadezimalion** [comment]
der originale Flyer hat noch eine Rückseite...

**Comment by midzer** [comment]
Done via https://github.com/freifunkMUC/freifunkmuc.github.io/commit/ae521bac1b7bfbf718aed88900e71bcf36a63d21 und weiteren commits in dem Bereich
