### ISSUE TITLE
Knotenstatistiken werden teilweise nicht angezeigt

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/freifunkmuc.github.io#95]
Die Knotenstatistiken werden teilweise nicht angezeigt.
Folgendes funktioniert (nicht):
- [x] map.freifunk-muenchen.de -> Graph -> Klick auf Knoten -> Grafana Stats, OK!
- [ ] map.freifunk-muenchen.de -> Statistik -> Linkt immer noch auf Munin
- [ ] map.freifunk-muenchen.de -> Knotendetails -> Linkt immer noch auf Munin
- [ ] map.freifunk-muenchen.de/meshviewer-stats -> Knotendetails -> 404 bei den Statistiken

**Comment by krombel** [comment]
map.freifunk-meuenchen.de gibt es nicht mehr
